# Generated by Django 3.2.7 on 2021-10-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20211001_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/image'),
        ),
    ]
