# Generated by Django 3.2.7 on 2021-10-03 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profile_image'),
        ('blogapp', '0005_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.profile'),
        ),
    ]
