# Generated by Django 3.2.7 on 2021-10-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_alter_mobile_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
